### ISSUE TITLE
resample_*: Resampling methods

### ISSUE THREAD

**Issue by m-mohr** [Open-EO/openeo-processes#14]
The resampling methods `resample_spatial` and `resample_temporal` are still very experimental and I honestly couldn't fully remember how we designed them in the VITO sprint. We probably need to check and describe better how the `target` parameter works. We also need to review whether the resampling methods work as expected and are complete, how upsampling could work (especially temporally) and whether the spatial resampling really should link to gdalwarp.

**Comment by lforesta** [comment]
> We probably need to check and describe better how the `target` parameter works

I agree, at the moment I don't know exactly how to create it, maybe with the processes create_raster_cube + add_dimension applied as many times as the dimensions needed? So it seems a user needs to explicitly generate an empty raster-cube in advance of using the resample processes.
Particularly for resample_spatial, maybe it would be easier from a user perspective to specify a target spatial resolution/sampling desired and let the back-end modify the existing raster-cube or create a new one.

**Comment by m-mohr** [comment]
Telco conclusions from today:
We need a new method for resampling based on actual parameters such as the resolution (see gdalwarp). We'll merge it with the new warp_projection methods and could call it resample_spatial. The other process we have at the moment, which spatially resamples from a given datacube to another datacube will be renamed. I think (after telco thoughts), this could be generalized to also allow temporal and other resampling from one data cube to another data cube. In this case the name could simply be resample_cube, resample_target or so.

**Comment by m-mohr** [comment]
Note from @claxn in the warp_projection PR (#28):
> Just a small comment from my side: In my opinion it would be convenient to specify a generic function warp(raster_cube_source, raster_cube_target, resampling_method). As you have mentioned in the meeting today, the datacube object should have all spatial related properties (e.g. extent, projection, pixel spacing...). If the extent is different, you will get the same result as with filter_bbox, if you you want to resample the data (e.g. downsampling 10m->500m), then you change the spatial resolution of the target datacube and if you want to reproject, then you change the projection system of the target datacube. Then we would have only one function instead of multiple. Moreover, a function clone_raster_cube (i.e. copying all properties from a raster cube and creating an empty one) could be helpful in case a user only has to change one property instead of specifying all spatial attributes.

**Comment by m-mohr** [comment]
@claxn It sounds like you are only speaking about spatial warping, so it doesn't affect or allow temporal dimensions for example. Foes the term warping imply spatial?

I like the idea to add a clone_cube process, see #32.

@mkadunc I assume proprietary ways are always not the way to go for an interoperable API, but it feels very difficult to describe this to an extent, which really works for all cases. At least I don't know yet how to describe it properly.

**Comment by claxn** [comment]
@mkadunc, @m-mohr : Yes, it would be great to clearly define what a data/raster cube is in general and how its axes are defined. I have read a bit into data cubes as EODC needs to implement one for another project (see [Open Data Cube](https://www.opendatacube.org/)). Within the frame of Open Data Cube, you have two spatial axes (e.g. x and y), a time axis and various bands per timestamp (i.e. different measurements). If we follow such a convention, I would keep the definition of a new data cube simple and focus on the spatial dimensions:

- PROJ4 parameters defining the projection/spatial reference system
- an extent (coordinates should be given in the same projection)
- spatial resolution (also in the same metric system, i.e. meter or degree)

The properties above will be modified by the user, when doing a warp operation. I would keep the other "axes" the same, since the operation should be finally applied on every 2D image inside the raster cube. 
  
@m-mohr: That's a good point. Yes, I may be a bit biased using GDAL, but I would consider it to take place in space only. Because modifications along the other dimensions should be done by other functions (e.g. temporal filtering along the time axis, band math, ...). I would see such a "warp" operation as fully responsible for all modifications in space.

**Comment by m-mohr** [comment]
Telco results:
Open questions are whether to include the following parameters from GDAL:
- **te** xmin ymin xmax ymax: set georeferenced extents of output file to be created (in target SRS by default, or in the SRS specified with -te_srs)
- **tap**: (GDAL >= 1.8.0) (target aligned pixels) align the coordinates of the extent of the output file to the values of the -tr, such that the aligned extent includes the minimum extent.

I'll look into it and add them if necessary.

We may also want to improve the description as discussed above by @claxn and @mkadunc , but we may shift it to v0.5 or so. At least I'm not feeling in the position to define these properties at the moment.

**Comment by m-mohr** [comment]
* **te*: to be set via filter_bbox or implicitly clear by data cube extents
* **tap**: Added as `align` parameter
* **tr**: Was already available as `resolution` parameter, but extended to allow to resample x and y separately.

**Comment by kempenep** [comment]
@m-mohr would it not make more sense to set default value of parameter `align` to upper left?
https://github.com/Open-EO/openeo-processes/blob/e9964f26e8e28d6ccc3c437520ff416bd1f99b93/resample_spatial.json#L97

**Comment by m-mohr** [comment]
@kempenep I implemented it as discussed in a telco. Personally, I don't have a preference. Could you elaborate yours? And maybe put your suggestion in a new issue so that it get's more traction and others can discuss. In a closed issue it may get lost...
