### ISSUE TITLE
`data` parameter for `all` and `any` processes

### ISSUE THREAD

**Issue by soxofaan** [Open-EO/openeo-processes#147]
almost all processes under the "reducer" category of https://openeo.org/documentation/1.0/processes.html  have `data` as first parameter (e.g. mean, max, sum, variance, ...)

exception are  `all` and `any` , which use `value` instead. It would probably make things cleaner if they also use `data` instead

**Comment by m-mohr** [comment]
Depends on which category you look into (logic with the `if` process is the other one).

In general, I tried to follow the following "conventions":

* data for all data cubes / numeric arrays
* value(s) for all boolean value(s)
* x/y for single values

I thought there are more processes with value(s) as parameter name, but it seems it's only if and any/all. So I'd be fine with using `data` in `any`/`all` and `x` (or something better) in `if`, but would leave this open for vote because I'd like to not break existing 1.0 implementations if there are any at the time we go RC2 or final.

**Comment by soxofaan** [comment]
another reason to prefer `data` over `value` in the case of `all`/`any`: `data` implies being a collection of some sorts (array, list, dictionary, cube, ...), while `value` sounds a lot more "scalar" to me (int, float, string).

But anyway, it was just a small observation, I don't have strong feelings about this.

**Comment by m-mohr** [comment]
Just to clarify: For any/all the name is "values" (it accepts multiple values) and only "if" uses "value" (it accepts a single value). So the plural should also imply collection. And yes, it's scalars in that case (boolean), although this would also true for numbers and for them it's data. Don't take this as vote for one or the other though.

**Comment by m-mohr** [comment]
Looking at the Hub, only VITO and GEE implement `any`, `all` and/or `if` at the moment . So I guess it's mostly up to us to decide whether to change this or not, @soxofaan 

I'm fine with renaming `values` to `data` in `any`/`all` and I think I'd leave `if` as it is. It's not up to VITO... ;-)
