### ISSUE TITLE
Decadal (10 year/10 day) periods in related processes

### ISSUE THREAD

**Issue by m-mohr** [Open-EO/openeo-processes#150]
We have some new processes:
* anomaly
* aggregate_temporal_frequency

The time periods supported are:
* hour
* day
* week
* month
* year
* season
* tropical-season
* single-period / climatology-period

In https://github.com/Open-EO/openeo-processes/pull/145#discussion_r394335478 discussions came up to also support decadal periods:
* 10 years
* 10 days per month (splitting a month into three parts, i.e. days 1-10, days 11-20 and days 21-31)

A problem was to find suitable names for the periods as decade/decadal is used for both years and days. 

See the mentions PR for more background. Should we add one of these or both?

cc @jwagemann @soxofaan @claxn

**Comment by m-mohr** [comment]
For future reference, here's how decade (10 years) was documented in the lists of options:
* `decade`: `YYY0` (first year of the decade)
* `decade`: Four-digit year number for the first year of each decade.
* `decade`: 10 year period, starting from years ending in a 0 to years ending in a 9 (e.g. 1990 - 1999).

**Comment by claxn** [comment]
If we go for decade (10 years), I prefer the first option, because it is the most simple one. 

@m-mohr : Referring to your last comment in https://github.com/Open-EO/openeo-processes/pull/145#discussion_r395663538: I like the idea of "decadal-per-month", but I am still open of tri-monthly with a good documentation.

**Comment by m-mohr** [comment]
Just for clarification @claxn, the three options above were used in different descriptions of the processes /parameters / return values in the PR and I just pasted them here so that I don't need to write them again in the future. They were not meant as option to choose from ;-) The texts slightly differ due to the context they were used in.

So what are the use cases for both 10 years and 10 days?

10 days:
* 10 day composites to close data gaps (@claxn)
* something at Vito? (@soxofaan)

10 years:
* ...

**Comment by jdries** [comment]
About 10-daily periods, and the use case:

- The name often used in literature is 'dekad' (so with a k instead of a c), if you google it, you'll see it appear in scientific remote sensing papers, so this seems to be accepted.
- I often refer to it as 10-daily period myself, which is a bit longer.
- Dekads are also understood to have a fixed position in the year, like months. So you can refer to the 6th dekad of 2020, and it's always the same period.
- The fact that the period is always the same, is very important for the use case: you can compare vegetation state in dekad 15 of 2020 with dekad 15 of 2019, and you're talking about exactly the same time period. (As opposed to weeks for instance, that shift slightly.)
- The use of 10-daily periods also comes from the fact that with current EO data, this is about the highest temporal resolution you can get with optical instruments, due to clouds. 
- Lower temporal resulution (like monthly) is often too coarse, as vegetation changes too quickly.

Hope this gives an overview on why these periods are used. Please pay attention to the fact that these dekads are often not random 10-daily periods, but indeed aligned within months, and the last dekad of the month is often not even 10-days long.

**Comment by m-mohr** [comment]
So the conclusion could be to add:
- "dekad": 10 day period. Three periods per month, day 1-10, 11-20 and 21-end of month, where the 3rd dekad of
the month can range from 8 to 11 days. Dekads are counted from the first day of each year, so the fourth dekad is the Feb, 1 - Feb, 2 each year.
- "decade": 10 year period, starting from years ending in a 0 to years ending in a 9 (e.g. 1990 - 1999).

**Comment by soxofaan** [comment]
> so the fourth dekad is the Feb, 1 - Feb, 2
you probably mean 1st of Feb until (and including) Feb 10th

But apart from that, that's also how I understand "dekad" and "decade"

**Comment by m-mohr** [comment]
Yes, indeed. That was a typo.

**Comment by m-mohr** [comment]
Check how to support: [decade-0](https://en.wikipedia.org/wiki/Decade#0-to-9_decade), [decade-1](https://en.wikipedia.org/wiki/Decade#1-to-0_decade)
