### ISSUE TITLE
merge_cubes: order of dimension labels after merge

### ISSUE THREAD

**Issue by m-mohr** [Open-EO/openeo-processes#212]
merge_cubes doesn't specify directly which order the dimension labels have been after the merge. It's implicitly clear that temporal and spatial likely have an order, but for band names for example it's not clear whether the bands are just concatenated or - for example - sorted. Behavior probably depends on the ref sys and if there's none than it concatenation, but it should be clarified.

Example 1:
- temporal dimension labels cube1: 2018-..., 2020-...
- temporal dimension labels cube2: 2019-...
- I'd guess the result is 2018-..., 2019-..., 2020-...

Example 2:
- band dimension labels cube1: B1, B4
- band dimension labels cube2: B2, B5
- I'd guess the result is B1, B4, B2, B5, but others could think it's B1, B2, B4, B5 as for spatial and temporal it's also having an implicit order

Opinions? How is it implemented?

**Comment by soxofaan** [comment]
I don't have a strong opinion which one feels best. For spatial and temporal it seems most logical to auto-sort. For band/other dimensions: is it that big of an issue to leave it as an implementation detail? 

Side question: can labels in a  dimensions have mixed type (number and string)? If yes: how to define order for mix of number and strings? If no: what with merge_cube where first cube has number labels and second cube has string labels?

**Comment by lforesta** [comment]
@soxofaan it's not an implementation detail because `array_element` allows to get an element by index, so it has to be clear for the user if it's B1, B2, B4, B5 or B1, B4, B2, B5.

In our case it is sorted in the temporal dimension, but not on the spectral one, but indeed the user cannot know that, so I'm in favour of specifying that in the process definition.

As to what specify, I don't have a strong opinion. In principle we have `sort` to sort a dimension, but it feels clunky to leave it to the user to having to use sort on every dimension, after having used `merge_cubes`...
I guess I would expect the 'continuous' dimensions to be sorted in ascending order (this includes spectral if you think of the wavelenght), and categorical ones to be in alphabetical order.

**Comment by m-mohr** [comment]
I have written the processes with the following expectations in mind:

- spatial and temporal have a natural order that is always in place
- bands (not necessarily spectral) are ordered as specified in metadata or processes, e.g. load_collection and filter_bands explicitly state that the order of the given array matters
- all other dimension types are also ordered as specified in metadata or processes
- For both bands and other dimension types, new labels are appended, e.g. see my merge_cubes example above

In theory dimension labels could be mixed types, yes.

**Comment by soxofaan** [comment]
> because array_element allows to get an element by index, 

yes indeed I thought about that too, and was thinking to recommend against using index based `array_element` after a `merge_cubes`. But specifying resulting order in process definition is probably better indeed.

giving it some more thought, I agree with what @m-mohr  proposes:
- dimensions with natural/inherit label order (spatial and temporal): autosort 
- band/other dimensions (where there is no inherit order): don't autosort, just append new labels
