### ISSUE TITLE
add_dimension: make `type` required parameter?

### ISSUE THREAD

**Issue by soxofaan** [Open-EO/openeo-processes#213]
from discussion at Open-EO/openeo-geopyspark-driver#55:

the default dimension `type` of `add_dimension` is `other`, but that is probably the least useful and least supported dimension type. 
Making `type` a required argument without default is probably better (principle of least surprise)

**Comment by soxofaan** [comment]
alternative solution: add an  `UnsupportedDimensionType` exception to the process?

**Comment by m-mohr** [comment]
Ideally, if "other" is not supported, it could just be removed from the enum. This won't work so well in this case because it's the default value. I'd be fine with making it required, but it's a breaking change. For now you can just change it and diverge a bit from the spec, I think. To throw an exception for the default value seems a bit odd.

The initial idea was that "other" would work for many cases, e.g. bands and temporal. It looses any type specific "improvements" or behavior, but still works in many cases. That it is surprising is a bit back-end specific as "other" is not supported, for other back-ends it might not be so surprising as it just "works".

I did not expect that "other" could be unsupported by back-ends, but nobody raised that during any of the meetings either.
