### ISSUE TITLE
Documentation of (CARD4L) ARD processes

### ISSUE THREAD

**Issue by jdries** [Open-EO/openeo-processes#228]
Based on review remark, which mentions that the documentation is rather sparse.
- ard_normalized_radar_backscatter does not mention the bands that are added by default, and their names
- ard_surface_reflectance : CARD4L specifies metadata bands to be added, but the process doesn't mention any of this

In general: maybe it can link to code samples? For instance:
https://open-eo.github.io/openeo-python-client/ard.html#atmospheric-correction
We point to processes.openeo.org a lot, which in it current form never mentions how to actually run things. 

Can we also extend the description, perhaps by even copying from the CARD4L description, so people don't have to go and read the PDF?

**Comment by m-mohr** [comment]
Yeah, we did not copy the information over from sar_backscatter for example. There it is defined how the bands will be named etc. We can simply copy that over.

It's the same for surface reflectance, many of the missing information is in the underlying processes for atmospheric_correction and cloud_detection. Here it's not 100% clear though what is returned as we don't know to what extend different cloud masks are available.

**Comment by m-mohr** [comment]
@jdries What do you want me to add from the CARD4L spec?

Linking to the library docs: I'm a bit hesitant as things are still in flux, in theory, processes are independent of implementations in clients and we should probably discuss a structure to not just make this yet another "about" link.

I've opened PR #229 for improvements. For now just SAR and I'll work on SR next. Is SAR how you expected it to be?

**Comment by m-mohr** [comment]
> ard_surface_reflectance : CARD4L specifies metadata bands to be added, but the process doesn't mention any of this

@jdries Could you please point me to where this is specified? I can't find it in the CARD4L spec.

**Comment by jdries** [comment]
I believe this is the full list:
2.2 No Data -> threshold
2.3 Incomplete Testing  -> threshold
2.4 Saturation  -> threshold
2.5 Cloud  -> threshold
2.6 Cloud Shadow  -> threshold
2.7 Land/Water Mask
2.8 Snow/Ice Mask
2.9 Terrain Shadow Mask
2.10 Terrain Occlusion
2.11 Solar and Viewing Geometry -> threshold: provide average
2.12 Terrain Illumination Correction
2.13 Aerosol Optical Depth Parameters

So looking at this, it the cloud bitmask seems to be the most relevant.

**Comment by m-mohr** [comment]
@jdries @lforesta What bands names have you implemented for all these? Otherwise I'll just use the names that correspond to STAC CARD4L.

**Comment by m-mohr** [comment]
> Is it an option to specify band names to be used if a backend does want to add these additional bands?

I don't understand. The (threshold) bands need to be generated by the back-ends and the data cube must return specific names so that user can rely on them. So I'd just specify a list of band names in the return value description.

**Comment by jdries** [comment]
Yes, agreed to specify band names in the return value. Nodata is usually encoded directly in the data, and sometimes also in the cloudmask, but indeed not as a separate band. Also cloud, cloud-shadow and saturation can be encoded in the same file.

One well-known example for sen2cor:
![image](https://user-images.githubusercontent.com/5937096/113423377-a70b1700-93ce-11eb-8e76-cd24abf33930.png)

**Comment by lforesta** [comment]
> @jdries @lforesta What bands names have you implemented for all these? Otherwise I'll just use the names that correspond to STAC CARD4L.

hmn, we don't provide them as bands yet

**Comment by jdries** [comment]
For VITO processes, angles need to be loaded from L1C, with these names:
"VAA", "VZA", "SAA", "SZA" 
or the full version:
viewAzimuthAngles, viewZenithAngles, sunAzimuthAngles, sunZenithAngles
AOT is generally used for aerosol
SNW is used by sentinelhub for snow band

The terrain stuff is also new to me.

**Comment by m-mohr** [comment]
Below there's a first attempt based on naming in STAC CARD4L (the naming from VITO doesn't seem easy to understand). See also #229 for all changes.

---

Data cube containing bottom of atmosphere reflectances for each spectral band in the source data cube, with atmospheric disturbances like clouds and cloud shadows removed. No-data values (null) are directly set in the bands. Depending on the methods used, several additional bands will be added to the data cube:

- `date` (optional): Specifies per-pixel acquisition timestamps.
- `incomplete-testing` (required): Identifies pixels  for which the per-pixel tests have not all been successfully completed with a value of 1. Otherwise the value is 0.
- `saturation` (required) / `saturation_{band}` (optional): Indicates where pixels in the input spectral bands are saturated (1) or not (0). If the saturation is given per band, the band names are `saturation_{band}` with `{band}` being the band name from the source data cube.
- `cloud`, `shadow` (both required),`aerosol`, `haze`, `ozone`, `water_vapor` (all optional): Indicates the probability of pixels being an atmospheric disturbances such as clouds. All bands have values between 0 (clear) and 1, which describes the probability that it is an atmospheric disturbance.
- `snow-ice` (optional): Points to a file that indicates whether a pixel is assessed as being snow/ice (1) or not (0). All values describes the probability and must be between 0 and 1.
- `land-water` (optional): Indicates whether a pixel is assessed as being land (1) or water (0).  All values describes the probability and must be between 0 and 1.
- `incidence-angle` (optional): Specifies per-pixel incidence angles in degrees.
- `azimuth` (optional): Specifies per-pixel azimuth angles in degrees.
- `sun-azimuth:` (optional): Specifies per-pixel sun azimuth angles in degrees.
- `sun-elevation` (optional): Specifies per-pixel sun elevation angles in degrees.
- `terrain-shadow` (optional): Indicates with a value of 1 whether a pixel is not directly illuminated due to terrain shadowing. Otherwise the value is 0.
- `terrain-occlusion`  (optional): Indicates with a value of 1 whether a pixel is not visible to the sensor due to terrain occlusion during off-nadir viewing. Otherwise the value is 0.
- `terrain-illumination`  (optional): Contains coefficients used for terrain illumination correction are provided for each pixel.

The data returned is CARD4L compliant and contains metadata.

**Comment by m-mohr** [comment]
Merged, see PR for details.
