### ISSUE TITLE
output and debug

### ISSUE THREAD

**Issue by lforesta** [Open-EO/openeo-processes#24]
Has anyone started including these two processes on a back-end and if so what kind of data and/or debugging info do you return? Maybe we could define this better or simply provide some examples in the description.

**Comment by m-mohr** [comment]
AFAIK no back-end except the GEE back-end has implemented the Subscriptions API yet, which is the basis for these processes. I'm still thinking about how these processes can look like, but I think these outputs highly depend on the back-end, too. In the GEE driver the output of `output` could be equal to what the GEE print operation offers.

**Comment by jdries** [comment]
For Geopyspark, it will not be easy to provide something meaningful. So I don't have these processes on my planning. I also don't know what GEE prints as debugging output, that might provide some ideas...

**Comment by m-mohr** [comment]
For interoperability reasons it could be useful to provide stubs anyway, @jdries, so that process graphs using these functions work anyway, but without doing anything. But that's probably something for fine-tuning at a later stage.

Some GEE examples:
![image](https://user-images.githubusercontent.com/8262166/52411430-1715ff00-2adc-11e9-8c78-18ea5a9da520.png)

**Comment by m-mohr** [comment]
Reworked in commit 57c7a0cc503e98bc64e25cfd4f94fa8dc1b17c58
