### ISSUE TITLE
dimension parameter name consistency

### ISSUE THREAD

**Issue by soxofaan** [Open-EO/openeo-processes#305]
While reviewing https://github.com/Open-EO/openeo-python-driver/pull/97, https://github.com/Open-EO/openeo-geopyspark-driver/pull/119 and https://github.com/Open-EO/openeo-python-client/pull/257 , I noticed this minor inconsistency  of the name of the dimension parameter in a couple of related processes: 

- `add_dimension(... name ...)`, `rename_dimension(... source, target )`
- `apply_dimension(... dimension ...)`, `reduce_dimension(... dimension ...)`
- `dimension_labels(... dimension ...)`
- `drop_dimension(... name ...)`
- `rename_labels(... dimension ...)`

I understand to be more explicit in `add_dimension` and `rename_dimension`,  
but it seems like `drop_dimension` should have used `dimension` as parameter name.

Obviously, fixing this would be  breaking change

**Comment by m-mohr** [comment]
For me it makes sense the way it is, but I can understand that this can get confusing.

Let me explain why I've chosen these names:
- rename_dimension is an exception, because you have two dimension names so neither name nor dimension would've worked and just appending numbers (e.g. 1,2) is not very straightforward, too. I could've names them new_name and old_name, but I've tried to stay with one word parameter names as much as possible.
- The idea was to use "name" as long as the main focus of the process is to manage the dimension (add <-> drop) and/or it refers directly to one of the properties of the dimension (see glossary). The connection to the dimension is clear as it's the main goal to change something about a dimension and it's in the process name.
- I've used dimension once the focus shifted towards working on the data (reduce_dimension, apply_dimension - here name could also refer to something else, e.g. a reducer name such as min) or the connection is not clear (rename_labels, dimension_labels - here it's not clear whether name refers to the dimension or label part of the process name).

I hope that helps. I think I could've indeed also used dimension as parameter names in add and drop dimension, but I guess this is really not a huge issue overall and I don't think it's important enough to do a breaking change (also in the future). I hope you agree? Otherwise, let me know.
