### ISSUE TITLE
Inconsistencies in processes (based on pydantic tests)

### ISSUE THREAD

**Issue by m-mohr** [Open-EO/openeo-processes#318]
We created [Pydantic](https://pydantic-docs.helpmanual.io/) Classes from the OpenEO API JSON process graph specification and tested them against the standard processes (from https://raw.githubusercontent.com/Open-EO/openeo-processes/1.x.0/)
We found that  ['array_apply', 'array_filter']  use 
<code>schema": [ {"type": "number"}, . . .  {"type": "null"}</code>
instead of 
<code>"schema": { "type": ["number", "string", "null"]}</code>
 
So, 
1. Is there any interest in discussing this matter? 
2. What would be the consequences of updating the standard processes accordingly?
3. Maybe the tests and models are of interest?

Running the tests against other lists of standard processes reveals other inconsistencies. Not sure how to proceed here in a way that benefits all. PS. the reason we used Pydantic is that [FastAPI](https://fastapi.tiangolo.com/) gives us automatic checking of the API parameters)

_Originally posted by @danielFlemstrom in https://github.com/Open-EO/openeo-processes/issues/204#issuecomment-1013146815_

**Comment by m-mohr** [comment]
Hey @danielFlemstrom,

I'm a bit confused and I think I need a bit more context here.

- It seems the terminology is a bit off here. Did you create pydantic classes for the openEO process schema? Because I'm not exactly sure how you could validate processes against a process graph schema.
- Yes, processes use different ways to make schemas available (schema vs. array of schemas). It depends on the use case and the data types that will be made available. Especially, we don't try to conflate different basic data types (except for null) so that data types can be described clearly and unambiguous. Both options shown above are valid.
- Regarding your three points:
  1. Yes.
  2. I'm not sure exactly what you want to align and why.
  3. Not sure yet, I'm not using Python a lot right now. It seems they would need some fine-tuning though.
- We try to minimize inconsistencies, but it might be that not all things that look like inconsistencies are really inconsistencies. I'm happy to discuss though. I'd hope to spot things that we can improve. How can I access the results of these tests?

**Comment by danielFlemstrom** [comment]
Hi @m-mohr!
Thank you for your quick response. Sorry for the confusion. I am relatively new to all this.
As you correctly say, the input is not a python process directly but, one of the Pydantic classes "down the road" is. As a result,  a process graph will not be accepted if it includes "non-conformant" processes.
Maybe the most efficient way to access the results of the tests is that I walk you through it in a T-EAMS or Zoom session? Of course, I can zip the models and the test case and mail it to you as well.

All the best
/Daniel
From: Matthias Mohr ***@***.***>
Reply to: Open-EO/openeo-processes ***@***.***>
Date: Friday, 14 January 2022 at 17:44
To: Open-EO/openeo-processes ***@***.***>
Cc: Daniel Flemström ***@***.***>, Mention ***@***.***>
Subject: Re: [Open-EO/openeo-processes] Inconsistencies in processes (based on pydantic tests) (Issue #318)


Hey @danielFlemstrom<https://eur05.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FdanielFlemstrom&data=04%7C01%7Cdaniel.flemstrom%40ri.se%7Ce02c1288ad03445a27a608d9d77d26ee%7C5a9809cf0bcb413a838a09ecc40cc9e8%7C0%7C0%7C637777754785630187%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=7WzoWarQd2aUuPmJN9PX8KZG5s6gLJc91visI1QWtEM%3D&reserved=0>,

I'm a bit confused and I think I need a bit more context here.

  *   It seems the terminology is a bit off here. Did you create pydantic classes for the openEO process schema? Because I'm not exactly sure how you could validate processes against a process graph schema.
  *   Yes, processes use different ways to make schemas available (schema vs. array of schemas). It depends on the use case and the data types that will be made available. Especially, we don't try to conflate different basic data types (except for null) so that data types can be described clearly and unambiguous. Both options shown above are valid.
  *   Regarding your three points:
     *   Yes.
     *   I'm not sure exactly what you want to align and why.
     *   Not sure yet, I'm not using Python a lot right now. It seems they would need some fine-tuning though.
  *   We try to minimize inconsistencies, but it might be that not all things that look like inconsistencies are really inconsistencies. I'm happy to discuss though. I'd hope to spot things that we can improve. How can I access the results of these tests?

—
Reply to this email directly, view it on GitHub<https://eur05.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FOpen-EO%2Fopeneo-processes%2Fissues%2F318%23issuecomment-1013284772&data=04%7C01%7Cdaniel.flemstrom%40ri.se%7Ce02c1288ad03445a27a608d9d77d26ee%7C5a9809cf0bcb413a838a09ecc40cc9e8%7C0%7C0%7C637777754785630187%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=1i2JEc4tB8k3bp9Bkgb2nyPxr0tCYKga5IvC3ZwW2lA%3D&reserved=0>, or unsubscribe<https://eur05.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAC6V5NV6LNJCFHXVXVDWW2LUWBHHJANCNFSM5L7IMX7A&data=04%7C01%7Cdaniel.flemstrom%40ri.se%7Ce02c1288ad03445a27a608d9d77d26ee%7C5a9809cf0bcb413a838a09ecc40cc9e8%7C0%7C0%7C637777754785630187%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=wY3gjP1j3hGv1vcOj17H3YRD2%2BJG4Dy5B1qLnRZX8I4%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://eur05.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7Cdaniel.flemstrom%40ri.se%7Ce02c1288ad03445a27a608d9d77d26ee%7C5a9809cf0bcb413a838a09ecc40cc9e8%7C0%7C0%7C637777754785630187%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=5wOM%2FPVqHYE2LWZZM72I%2BxGMhBlTRv%2F8MGqMzwYAoXc%3D&reserved=0> or Android<https://eur05.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7Cdaniel.flemstrom%40ri.se%7Ce02c1288ad03445a27a608d9d77d26ee%7C5a9809cf0bcb413a838a09ecc40cc9e8%7C0%7C0%7C637777754785630187%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=t%2BKtvgG%2FZYrvbhe%2Ff2ZhkMlnX2RbjuhNqE9Rn3%2Bm8Jw%3D&reserved=0>.

**Comment by m-mohr** [comment]
Happy to join a Teams of Zoom session. That seems indeed like the most efficient way. I'm pretty flexible with meeting slots this week (e.g. today until 4), you could just send an invite. My e-mail address is in my GitHub profile. Thank you!

**Comment by m-mohr** [comment]
Clarified the issues on a video call. Thank you again for your contribution.
