### ISSUE TITLE
Add clone_cube 

### ISSUE THREAD

**Issue by m-mohr** [Open-EO/openeo-processes#32]
Suggestion from @claxn: 
> Moreover, a function clone_raster_cube (i.e. copying all properties from a raster cube and creating an empty one) could be helpful in case a user only has to change one property instead of specifying all spatial attributes.

Does that sound helpful to everybody? I assume the values would all be set to no data (null)?

Could be someting like:

`clone_cube(raster_cube cube, ?boolean clone_values = false) : raster_cube`

clone values = false => Set all values to null (no data)
clone values = true => Copy also the pixel values

**Comment by claxn** [comment]
Sounds good! I am not sure what a user could do with an empty, cloned data cube except requesting its properties or using it in other functions such as warp. Are there any restrictions that a data cube has to be depictable (one can visualise it on a map)? If yes, then the above notation suits well. If no, we could save some time and only copy its properties. Nevertheless, I would prefer your definition and the output, since the data cube then preserves the bands and the temporal dimension and will be easier to handle.

**Comment by m-mohr** [comment]
Yes, we agreed here after some discussion that we would need to define additional processes that allow changing the data cube, e.g. properties, dimension values etc. But currently we don't have such processes and so we had no ideas for use cases we could need this for. There are probably some use cases, so I'd leave this issue open to be solved later once we also define the mentioned processes that work on properties, dimension values etc.

**Comment by edzer** [comment]
Currently what one would need to do is call a `resample_xxx` with a source datacube and target cube parameters, rather than a parameterized target cube (which we can't construct freely).

**Comment by m-mohr** [comment]
Telco: We don't have a use case for it at the moment.
