### ISSUE TITLE
fit_class_random_forest: better name for `mtry` parameter

### ISSUE THREAD

**Issue by soxofaan** [Open-EO/openeo-processes#339]
GeoPySpark -> max_bins
scikit-learn -> max_features

_Originally posted by @m-mohr in https://github.com/Open-EO/openeo-processes/pull/306#discussion_r822666272_

**Comment by soxofaan** [comment]
In most processes we try to come up with non-cryptic, self-describing parameter names.
I think `mtry` in `fit_class_random_forest`  is "off-brand" here

I currently have no preference for a better alternative, I just wanted to reopen this to-do

**Comment by soxofaan** [comment]
I'm aware of the background, but I don't think we should take FORTRAN as a naming convention reference  in a modern/new query language/API   :stuck_out_tongue: 

Nevertheless if `mtry` is a well established concept in the EO/ML community, I'm fine to accept it as-is. It's just that there is nothing to me in those four characters that even hints at what it's about.

@clausmichele @mattia6690 @LukeWeidenwalker  do you have an opinion on this?

**Comment by mattia6690** [comment]
Well, since the processes are implemented using Python I assume that we could change to `max_features`. It might also be a bit confusing as it does not indicated that the "max_features" are linked to each split but I agree that it is easier to understand on first sight than `mtry`. 
However - if changed - I would add to the process description that it refers to the `mtry` parameter in the original Fortran RF implementation. This allows users from different programming backgrounds to connect the dots and understand our implementation

**Comment by m-mohr** [comment]
> Well, since the processes are implemented using Python

That's not a good reason. Our decisions should not be based on a single implementation/language. 

Nevertheless, I agree with the rest of the comment.

**Comment by m-mohr** [comment]
Interestingly, our parameter description doesn't talk about features (or bins). Instead, it says:

> Specifies how many split variables will be used at a node.

From the description itself, I'd think about something like `split_variables` or `max_variables.`

**Comment by m-mohr** [comment]
@ all: Please review PR #351
