### ISSUE TITLE
process to convert inline GeoJSON to a vector cube

### ISSUE THREAD

**Issue by soxofaan** [Open-EO/openeo-processes#346]
Closely related to #343 (or maybe even a duplicate):

(do) we need a process that converts inline GeoJSON to a vector-cube

**Comment by soxofaan** [comment]
Still, regardless of #343, it could be useful to have an explicit process that can be more powerful compared to doing implicit conversions with best effort defaults.

e.g. possible features/options to think of or include:
- handle Polygon/MultiPolygon by implicitly handling them as single-feature feature collections
- automatically add a unique (e.g. auto-increment int) "id" property
- drop provided properties, or enforce missing properties with a default

**Comment by m-mohr** [comment]
How's the relation to load_files? In principle, it doesn't matter where the GeoJSON is coming from, but you have the same issues or parameters to influence loading/converting the data. Thus, it's a bit strange to have a dedicated process for inline geojson, but then a completely different process for loading all kinds of files in load_files.

**Comment by soxofaan** [comment]
Good point, there would indeed be quite some overlap.

An alternative is defining a process like `load_vectorcube` , which would be the vector-equivalent of what `load_collection` is for raster cubes. It could accept several source types:
1. (inline) JSON object, to be interpreted as GeoJSON/JSON-FG
2. relative path (string) for loading vector date from user workspace
3. URL string(s) for loading vector data from URL

or we add 1. to the current `load_files` proposal of #322, and find a more generic name than "file" so that it isn't weird to load inline GeoJSON that way

**Comment by m-mohr** [comment]
load_collection could also load a vector-cube, if you expose vector data from the back-end side at /collections. Also, the second word in load_* processes always refers to the origin, not to what is returned.

The issue on the other hand with load_files is that it's weird to mix in inline stuff. This doesn't necessarily only need to be GeoJSON, you could also inline CovJSON at some point. And then it gets messy. 

The underlying issue here is that the processes don't really know about files and formats. This is all handled through /file_formats right now, also for raster. And in that sense GeoJSON is not different, but seems to have some kind of special handling right now due to being easily includable in process graphs. So what we may need to start at the openEO level at some point is to document best practices around file formats, similar to how we do it in Platform already a bit: https://docs.openeo.cloud/federation/backends/fileformats.html

This is challenging though as for some formats the conversion is not really clear (GeoTiff), while for GeoJSON to vector-cubes it might be a bit clearer.
