### ISSUE TITLE
Get rid of GeometryCollection

### ISSUE THREAD

**Issue by m-mohr** [Open-EO/openeo-processes#389]
We are working towards v2 of the processes for vector cubes. I think this is a good chance to disallow and remove the already "not recommended" GeometryCollection from the processes.

Thoughts?

**Comment by soxofaan** [comment]
Getting rid of GeometryCollection as an allowed geometry type simplifies things for backend implementors, so that's good.
I have no idea if it is a valuable type for real use cases and end users.

Related: https://github.com/Open-EO/openeo-python-driver/issues/71  (in  VITO backend we handle a GeometryCollection as a feature collection, and we want to get rid of that inconsistency)

**Comment by m-mohr** [comment]
PR #289 proposes to remove GeometryCollection. It has been deprecated in 1.1.0 and as such is a good candidate for removal in 2.0.0.

**Comment by soxofaan** [comment]
> PR #289 proposes to ...

I guess you meant PR #395 ?
