### ISSUE TITLE
POC Use Case 2 with UDFs in the new version?

### ISSUE THREAD

**Issue by m-mohr** [Open-EO/openeo-processes#45]
I'm currently trying to migrate the old proof of concept use cases to the new processes and I'm stuck with the UDFs in Use Case 2, see https://open-eo.github.io/openeo-api/v/0.3.1/examples-poc/#3-create-a-job.

I see two issues:
* How do I pass the data to the UDF? There's no parameter to pass it. 😳
* What exactly was the UDF doing? What did aggregate_time? Does it replace with reduce on the temporal dimension?

This is the current process graph, which probably won't work yet as I'm not passing the data received in the reduce function to the UDF:
```json
{
  "loadco1": {
    "process_id": "load_collection",
    "arguments": {
      "id": "Sentinel-1"
    }
  },
  "filter1": {
    "process_id": "filter_bbox",
    "arguments": {
      "data": {
        "from_node": "loadco1"
      },
      "extent": {
        "west": 16.1,
        "east": 16.6,
        "north": 48.6,
        "south": 47.2
      }
    }
  },
  "filter2": {
    "process_id": "filter_temporal",
    "arguments": {
      "data": {
        "from_node": "filter1"
      },
      "start": "2017-01-01",
      "end": "2017-02-01"
    }
  },
  "reduce1": {
    "process_id": "reduce",
    "arguments": {
      "data": {
        "from_node": "filter2"
      },
      "dimension": "temporal",
      "reducer": {
        "callback": {
          "runudf1": {
            "process_id": "run_udf",
            "arguments": {
              "udf": "s1_aggregate.py",
              "runtime": "Python"
            },
            "result": true
          }
        }
      }
    },
    "result": true
  }
}
```

JS code:
```js
var datacube = b.process("load_collection", {id: "Sentinel-1"});
datacube = b.process("filter_bbox", {data: datacube, extent: {
	west: 16.1,
	east: 16.6,
	north: 48.6,
	south: 47.2
}});
datacube = b.process("filter_temporal", {data: datacube, start: "2017-01-01", end: "2017-02-01"});
var aggregate = b.process("reduce", {
	data: datacube,
	dimension: "temporal",
	reducer: (builder, params) => builder.process("run_udf", {udf: "s1_aggregate.py", runtime: "Python"})
});
var createdProcessGraph = b.generate(aggregate);
```

**Comment by m-mohr** [comment]
So after thinking about where UDFs are used, I realized that it is actually not so easy to specify a `data` parameter for `run_udf` and `run_udf_externally`. For example, in `reduce` with `binary` set to `true` the UDF expects two separate primitive arguments. In `apply` the UDF expects a single primitive argument, in `apply_dimension` the UDF expects an array, etc. So we may need to treat the UDFs differently. We could just pass them in and let the back-end do magic to pass the values correctly, depending on the use case. So in the end the data doesn't get passed to the UDF processes and needs to be captured in the calling process. But how do we handle cases where a UDF is part of a bigger process chain and we actually don't know what should be passed? Lots of questions and I have no answers yet...

**Comment by pramitghosh** [comment]
In one of the strategies for R UDFs that was actually integrated with @flahn's R reference backend, the user (operating the client) specified which dimensions are to be modified by his/her UDF by registering it in the backend against (one of the) UDF processes (`apply_*` and so on...). Which dimensions are to be changed is associated with these UDF processes and represented with the help of a vector using a concept of "dimensionality" that we developed. All the user is expected to do is register his/her UDF against the correct UDF type depending on what it is doing and need not specify the dimensions himself/herself (that is taken care of by the backend).

Now, I believe, this solves the problem about having specific argument types (such as whether it is a scalar string that is to be passed or a vector or a number etc.) for each UDF in the backend. The user need not worry about whether he/she is reducing one dimensions or two dimensions as long as it is registered against the correct UDF process. Each UDF process could, however, have some specific arguments that the user can fill up.

Another thing that I have in mind is to develop some sort of an annotation in the actual UDF script (e.g. having this "dimensionality change" vector in the first line of the UDF script e.g. `#dimChange <0010>` - as far as I remember we followed the order `<space, band, time, raster>` but this, of course, is a matter of discussion and convention) so that this is parsed by the backend and assigned to the correct UDF process accordingly. Perhaps this makes things easier for the backend at the expense of usability from the users' PoV. This drops the need for specific processes for each UDF types in the backend.

Taking this a bit further, why is it so necessary to assign "types" for UDFs (unless we are taking about scalability)? Since it is the user who is creating the chain of processes, he/she would be aware of what is going into the UDF (i.e. what is the output of the previous process in the graph) and that's how the UDF itself is coded anyway. If the backend and the UDF service conforms to the UDF API, the user can do whatever he/she wants inside his/her UDF and the backend would still be able to understand the output since the consistency is enforced by the UDF API. The backend need not know whether the data is reduced (or anything else) in one, multiple or no dimensions at all. For scalability purposes, however, the backend needs to know in my opinion.

**Comment by m-mohr** [comment]
Annotations in UDFs don't help here as this is a thing between client and back-end (not between back-end and UDF server), so the information is not directly available to the user writing the process graph. We just need a way to pass the data to the UDF process itself in a way that it works for all processes that accept UDFs as callbacks. I hope we can avoid multiple processes to just call the UDFs, UDFs should be just used as any of the other processes. Not sure where you get from that UDFs have types, but in the current proposal for the processes they don't have types (yet?).

**Comment by pramitghosh** [comment]
Yes, I understand it is between the client and the backend, but perhaps I have a different picture for the UDFs. The question is whether the user knows what is the output of the previous process in the graph. I am assuming it is known by the user.

I think it would be possible to avoid multiple UDF processes in the backend. And if we are not assigning UDFs types, then I'm mistaken.

By these `data`, are you talking about something that is passed on from another process? Or are these supplied by the user?

**Comment by m-mohr** [comment]
Could be both. Let's see how it works with the arrays...

**Comment by m-mohr** [comment]
We could allow in addition to simply pass a whole raster data cube to the `run_udf` process.
