### ISSUE TITLE
filter_spatial vs filter_vector

### ISSUE THREAD

**Issue by soxofaan** [Open-EO/openeo-processes#460]
Not sure if there is still room to change a lot here, but while looking into vector cube issues I observed this:

- `filter_bbox` supports both raster and vector cubes
- `filter_spatial` supports only raster cubes and `filter_vector` support only vector cubes, but both work almost identical (assuming relation="intersect" in filter_vector). Is there some opportunity to unify this better, e.g. allow vector cubes in filter_spatial?

I think at least we should have better cross-referencing (documentation-wise) between these processes (there is no documentation link between filter_spatial and filter_vector)

**Comment by m-mohr** [comment]
I considered it, but based on the relation parameter I found it akward. 

You'd need to assume the Pixels are points at the pixel center, but I'm not sure whether you'd want to implement all the allowed relation types that you have for vectors also for rasters. What happens if you only support intersection for raster and all other relation types for vector? Confusing.

But indeed, crosslinking between them would be good.
