### ISSUE TITLE
Process examples (math and comparison)

### ISSUE THREAD

**Issue by claxn** [Open-EO/openeo-processes#49]
I am currently writing tests for the simple processes using the given examples. I stumbled upon some minor errors within the documentation (perhaps due to copying it from other process examples). My suggested corrections are given below (I aimed for correcting the result, not the input parameters):

- `min`: 
  - `min(data= [1,0,3,2]) => 0`
  - `min(data = [5,2.5,null,-0.7]) => -0.7`
  - `min(data = [1,0,3,null,2], ignore_nodata = false) => null`
  - `min(data = []) => null`
- `mod`: example `mod(x = 27, y = 5) => 2` repeated two times
- `arccos`: 
  - `arccos(x = 0) => pi/2`
- `arcosh`: 
  - `arccos(x = 0) => null/NaN`
- `eq`:
  - `eq(x = "2018-01-01T12:00:00Z", y = "2018-01-01T12:00:00") => true`
  - `eq(x = "2018-01-01T00:00:00Z", y = "2018-01-01T01:00:00+01:00") => true` (`T` instead of `Z`)
- `neq`: 
  - `neq(x = "2018-01-01T12:00:00Z", y = "2018-01-01T12:00:00") => false`
  - `neq(x = "2018-01-01T00:00:00Z", y = "2018-01-01T01:00:00+01:00") => false` (`T` instead of `Z`)
- `between`: 
  - `between(x = -0.5, min = 0, max = -1) => false` (`min` and `max` probably interchanged)
  - `between(x = "00:00:01+01:00", min = "00:00:00Z", max = "00:00:00+01:00") => false` (e.g. for `true` return value: `between(x="00:00:01-01:00", min="00:00:00Z", max="02:00:02+01:00"`)
  - `between(x = "2018-12-31T17:22:45Z", min = "2018-01-01", max = "2018-12-31") => false`

**Comment by m-mohr** [comment]
* min - Fixed, was probably copied from extrema.
* mod - Removed
* arccos - Changed to `arccos(x = 1) => 0`; I can't easily provide exact results pi/2
* arccosh - Changed to `arccosh(x = 1) => 0`; I can't easily encode NaN in JSON
* eq/neq
  * Fixed the T/Z issue. 
  * `eq(x = "2018-01-01T12:00:00Z", y = "2018-01-01T12:00:00") => true` - **Not fixed**, the latter is not a valid date time and therefore will be treated as a string. Therefore they are not equal. Same applies for the corresponding example in `neq`. I added a short description explaining the example.
  * `eq(x = "2018-01-01T00:00:00Z", y = "2018-01-01T01:00:00+01:00") => true` - **Not fixed**, 01:00 in the +1 timezone is equal to 00:00 in UTC. Same applies for the corresponding example in `neq`. I added a short description explaining the example. You can check examples with https://www.epochconverter.com/ and compare the unix timestamps.
* between
  * Fixed the first example.
  * Second example: Fixed by making the example even more evil. ;-) Please re-check the new examples.
  * Changed the example to use `exlude_max`, please re-check the new examples.

Thanks a lot, that happens if you work through 100+ processes all day long for weeks, but some examples really test edge cases that people don't think about usually. ;-)

**Comment by claxn** [comment]
Thanks a lot for your effort, @m-mohr! :-)  I can imagine how cumbersome it is to have an overview over so many processes and to manage everything... The examples are nice to be directly used as tests. I will do my best to provide some useful input, while I implement the processes. Some comments:

- arccos and arcosh: good to know, I have adapted my tests, too. 
- `eq`: 
  - Okay, now I understand. It seems I was not restrictive enough in parsing the datetime string (I will try to find a solution to exactly follow the RFC3339 convention)
  - As far as I remember everything was right before, there was only the a Z instead of a T. But anyway, it is good to have a description.
- `between`: 
  - Second example: haha great, its fine. ;-)
  - Third example: But this would be anyway false, wouldn't it? Do the `min` and `max` dates then equate to "2018-01-01T00:00:00Z" and "2018-12-31T00:00:00Z"?
  - I have included the `exclude_max` parameter, all tests/examples work.

**Comment by m-mohr** [comment]
Inspiration for the RFC3339 regexp: https://gist.github.com/marcelotmelo/b67f58a08bee6c2468f8

Regarding dates: 2018-01-01 is basically describing an interval, i.e. the whole day, so 2018-01-01T00:00:00Z until 2018-01-01T23:59:59Z (inclusive). That's why the last example returns false and the other one true.

**Comment by claxn** [comment]
Great, thanks!
