### ISSUE TITLE
normalized_difference: A datacube with two bands vs. two datacubes with one band

### ISSUE THREAD

**Issue by m-mohr** [Open-EO/openeo-processes#60]
I am currently trying to implement `normalized_difference`.

The process `normalized_difference` takes two datacubes, each having a band dimension holding a single band so you usually need to filter two times in advance. Example:

```
var collection  = load_collection("Sentinel-2");
var b1 = filter_bands(collection, ["B4"]);
var b2 = filter_bands(collection, ["B8"]);
var nd = normalized_difference(b1, b2);
```

This feels cumbersome. We could also allow:
```
var collection  = load_collection("Sentinel-2");
var nd = normalized_difference(collection, "B4", "B8");
```

Unfortunately, this is not easily to add to the other signature of normalized_difference. Also, if you get the bands from two collections (e.g. B8A and B4 would be different collections at EURAC) that would be more complicated then:

```
var collection10  = load_collection("Sentinel-2-10m");
var collection20  = load_collection("Sentinel-2-20m");
var collection10resampled = resample(collection10, "20m"); // That's not an actual process, just for making the point clear...
var collection = merge_cubes(collection10resampled, collection20);
var nd = normalized_difference(collection, "B4", "B8");
```

So, what do you think should we use? Wouldn't it in most cases be easier to just accept a single data cube with two bands?

**Comment by aljacob** [comment]
that depends on how people setup the data cubes. In some cases those might be one band per cube. Or are we saying that all bands have to be in the same collection as a definite rule for openEO data cubes? Otherwise overloading was not possible in the processes, right? So we could not have the same process with two different set of parameters? Or can we have a must have of one data cube and an optional second data cube. If only one is specified, then it is implicitly understood to read both bands from the same data cube, otherwise read the first band from first data cube and the second band from second data cube? What do you think?

**Comment by jdries** [comment]
I also did not yet implement this process, specifically because of having to combine multiple datacubes.
Also you usually do normalized difference between spectral bands of the same sensor, which are quite likely to be available in a single datacube.
I would opt for taking a datacube, and some kind of reference to two bands in that single cube.

**Comment by edzer** [comment]
I agree: it is essentially a reducer, and the band selector could be another process.

**Comment by m-mohr** [comment]
So basically somthing like `normalized_difference(datacube, bandName1 = null, bandName2 = null) : datacube`? If bandName1 and bandName2 are not set by the user, it expects just takes the first and second band (order set by filter_bands).

**Comment by m-mohr** [comment]
Telco: We'll make this a reducer: normalized_difference(number red, number nir).
